export const projects = [
  {
    id: 1,
    title: 'Social Media App',
    description: 'Scalable social media backend with real-time features, Redis caching, and BullMQ background jobs.',
    longDesc: 'A production-ready social media backend built with Node.js, Express, Redis, and BullMQ. Features include real-time feed updates, background notification jobs, Redis caching for hot data, and Dockerized deployment with CI/CD.',
    image: 'https://raw.githubusercontent.com/Eslamsaeed880/Social-Media-App/main/docs/main.png',
    imageAlt: 'Social Media App backend architecture diagram',
    tags: ['Node.js', 'Express', 'MongoDB', 'Redis', 'BullMQ', 'Testing', 'Docker', 'CI/CD', 'Recommendation System', 'Event Based', 'Caching Strategies', 'Logging', 'Rate Limit'],
    github: 'https://github.com/Eslamsaeed880/Social-Media-App',
    live: null,
    highlight: 'Redis + BullMQ',
    color: '#7C3AED',
  },
  {
    id: 3,
    title: 'Fitness API',
    description: 'Backend system for fitness tracking — workouts, nutrition, and user progress analytics.',
    longDesc: 'A modular, scalable backend API with caching (Redis), background jobs (BullMQ), containerization (Docker), CI/CD pipelines, and automated testing for optimized performance and maintainability. Core functionalities include workout logging, nutrition tracking, progress analytics, and user management. Advanced features comprise social feeds, a chat app with an AI coach, AI-assisted moderation, AI-generated personalized workouts, and AI-driven recommendations. This project is currently being refactored.',
    image: 'https://raw.githubusercontent.com/Eslamsaeed880/Fitness-API/main/images/Fitness.png',
    imageAlt: 'Fitness API dashboard with health metrics',
    tags: ['Node.js', 'Express', 'MongoDB', 'Redis', 'BullMQ', 'Docker', 'Modular Architecture', 'Socket.io', 'AI Recommendation Systems', 'Event Based', 'Caching Strategies', 'Logging', 'Rate Limit'],
    github: 'https://github.com/Eslamsaeed880/Fitness-API',
    live: null,
    highlight: 'Modular Architecture + AI Integerations',
    color: '#9F67FF',
  },
  {
    id: 2,
    title: 'E-Commerce API',
    description: 'Full-featured e-commerce REST API with auth, products, orders, and payment flow.',
    longDesc: 'A comprehensive e-commerce backend built with Node.js and Express. Implements JWT authentication, product catalog management, order processing, payment integrations, and structured REST API design with Swagger docs.',
    image: 'https://raw.githubusercontent.com/Eslamsaeed880/ecommerce/main/images/image2.png',
    imageAlt: 'E-Commerce API documentation and endpoints',
    tags: ['Node.js', 'Express', 'MongoDB', 'Stripe', 'JWT', 'Cloudinary'],
    github: 'https://github.com/Eslamsaeed880/ecommerce',
    live: null,
    highlight: 'Full Secure REST API',
    color: '#06B6D4',
  },
  {
    id: 4,
    title: 'Job Finder',
    description: 'Full-stack job search web application connecting job seekers with opportunities.',
    longDesc: 'A full-stack web application for job searching built with Python Django backend and HTML, CSS, and JavaScript frontend. Features job listings, advanced filtering, user profiles, application tracking, and a responsive UI.',
    image: 'https://raw.githubusercontent.com/Momen-Abdelkader/Job-Finder/main/frontend/assets/JobSearch.png',
    imageAlt: 'Job Finder application showing job listings',
    tags: ['Python', 'Django', 'JavaScript', 'Sqlite'],
    github: 'https://github.com/Momen-Abdelkader/Job-Finder',
    live: null,
    highlight: 'Full-Stack',
    color: '#F59E0B',
  },
];
